namespace Ats.ContinuousImprovement.DAL.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class v3 : DbMigration
    {
        public override void Up()
        {
            AddColumn("dbo.CIDocuments", "SiteProjectAppliesTo", c => c.Int(nullable: false));
            DropColumn("dbo.CIDocuments", "SiteName");
            DropColumn("dbo.CIDocuments", "Name");
            DropColumn("dbo.CIDocuments", "ProjectName");
            DropColumn("dbo.CIDocuments", "ProjectLead");
            DropColumn("dbo.CIDocuments", "Sponsor");
            DropColumn("dbo.CIDocuments", "StartDate");
            DropColumn("dbo.CIDocuments", "ExpectedClose");
            DropColumn("dbo.CIDocuments", "WorkCompleteDate");
            DropColumn("dbo.CIDocuments", "ProjectType");
            DropColumn("dbo.CIDocuments", "ProjectPhase");
            DropColumn("dbo.CIDocuments", "Benefits");
            DropColumn("dbo.CIDocuments", "ProjectStatus");
            DropColumn("dbo.CIDocuments", "ProjectedSavings");
            DropColumn("dbo.CIDocuments", "ATSActualSavings");
            DropColumn("dbo.CIDocuments", "ATSLevel1");
            DropColumn("dbo.CIDocuments", "CustLevel1");
            DropColumn("dbo.CIDocuments", "CustLevel3");
            DropColumn("dbo.CIDocuments", "CustActualSavings");
            DropColumn("dbo.CIDocuments", "FunctionalArea");
            DropColumn("dbo.CIDocuments", "Region");
            DropColumn("dbo.CIDocuments", "OneUpManager");
            DropColumn("dbo.CIDocuments", "Blackbelt");
            DropColumn("dbo.CIDocuments", "Workorder");
            DropColumn("dbo.CIDocuments", "OpenField1");
            DropColumn("dbo.CIDocuments", "OpenField2");
            DropColumn("dbo.CIDocuments", "FlagForDeletion");
            DropColumn("dbo.CIDocuments", "CustomerExpectedSavings");
            DropColumn("dbo.CIDocuments", "AtsExpectedSavings");
            DropColumn("dbo.CIDocuments", "TimeFrameSavings");
            DropColumn("dbo.CIDocuments", "DivisionNumber");
            DropColumn("dbo.CIDocuments", "OnePercentLevelOneEligible");
            DropColumn("dbo.CIDocuments", "TwoUpManager");
            DropColumn("dbo.CIDocuments", "ThreeUpManager");
            DropColumn("dbo.CIDocuments", "ActualSavings");
            DropColumn("dbo.CIDocuments", "ApprovalComments");
            DropColumn("dbo.CIDocuments", "AreaManager");
            DropColumn("dbo.CIDocuments", "AtsLevelOneDetails");
            DropColumn("dbo.CIDocuments", "AtsLevelTwo");
            DropColumn("dbo.CIDocuments", "AtsLevelTwoDetails");
            DropColumn("dbo.CIDocuments", "AtsLevelThree");
            DropColumn("dbo.CIDocuments", "AtsLevelThreeDetails");
            DropColumn("dbo.CIDocuments", "Auditor");
            DropColumn("dbo.CIDocuments", "CheckedOutTo");
            DropColumn("dbo.CIDocuments", "CiNumber");
            DropColumn("dbo.CIDocuments", "Classification");
            DropColumn("dbo.CIDocuments", "Comments");
            DropColumn("dbo.CIDocuments", "CompleteDate");
            DropColumn("dbo.CIDocuments", "CompletedDate");
            DropColumn("dbo.CIDocuments", "Contributors");
            DropColumn("dbo.CIDocuments", "Created");
            DropColumn("dbo.CIDocuments", "CreatedBy");
            DropColumn("dbo.CIDocuments", "CustFinancialEntryName");
            DropColumn("dbo.CIDocuments", "CustLevelOneDetails");
            DropColumn("dbo.CIDocuments", "CustLevelTwo");
            DropColumn("dbo.CIDocuments", "CustLevelTwoDetails");
            DropColumn("dbo.CIDocuments", "CustLevelThreeDetails");
            DropColumn("dbo.CIDocuments", "CustomerApproval");
            DropColumn("dbo.CIDocuments", "CustomerBlackbelt");
            DropColumn("dbo.CIDocuments", "EmployeeSiteNumber");
            DropColumn("dbo.CIDocuments", "LastAuditDate");
            DropColumn("dbo.CIDocuments", "LastAuditDateTwo");
            DropColumn("dbo.CIDocuments", "MeetsAuditRequirements");
            DropColumn("dbo.CIDocuments", "Modified");
            DropColumn("dbo.CIDocuments", "ModifiedBy");
            DropColumn("dbo.CIDocuments", "NextMeetingDate");
            DropColumn("dbo.CIDocuments", "Opprotunity");
            DropColumn("dbo.CIDocuments", "ProcessOwner");
            DropColumn("dbo.CIDocuments", "ProjectApprovalStatus");
            DropColumn("dbo.CIDocuments", "ProjectFlag");
            DropColumn("dbo.CIDocuments", "ReadyForApproval");
            DropColumn("dbo.CIDocuments", "SavingsLevel");
            DropColumn("dbo.CIDocuments", "SixSigma");
            DropColumn("dbo.CIDocuments", "Solution");
            DropColumn("dbo.CIDocuments", "SubmittedDate");
            DropColumn("dbo.CIDocuments", "Title");
            DropColumn("dbo.CIDocuments", "YearOneQuarterOne");
            DropColumn("dbo.CIDocuments", "YearOneQuarterTwo");
            DropColumn("dbo.CIDocuments", "YearOneQuarterThree");
            DropColumn("dbo.CIDocuments", "YearOneQuarterFour");
            DropColumn("dbo.CIDocuments", "YearTwoQuarterOne");
            DropColumn("dbo.CIDocuments", "YearTwoQuarterTwo");
            DropColumn("dbo.CIDocuments", "YearTwoQuarterThree");
            DropColumn("dbo.CIDocuments", "YearTwoQuarterFour");
        }
        
        public override void Down()
        {
            AddColumn("dbo.CIDocuments", "YearTwoQuarterFour", c => c.String());
            AddColumn("dbo.CIDocuments", "YearTwoQuarterThree", c => c.String());
            AddColumn("dbo.CIDocuments", "YearTwoQuarterTwo", c => c.String());
            AddColumn("dbo.CIDocuments", "YearTwoQuarterOne", c => c.String());
            AddColumn("dbo.CIDocuments", "YearOneQuarterFour", c => c.String());
            AddColumn("dbo.CIDocuments", "YearOneQuarterThree", c => c.String());
            AddColumn("dbo.CIDocuments", "YearOneQuarterTwo", c => c.String());
            AddColumn("dbo.CIDocuments", "YearOneQuarterOne", c => c.String());
            AddColumn("dbo.CIDocuments", "Title", c => c.String());
            AddColumn("dbo.CIDocuments", "SubmittedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "Solution", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "SixSigma", c => c.Boolean(nullable: false));
            AddColumn("dbo.CIDocuments", "SavingsLevel", c => c.Int(nullable: false));
            AddColumn("dbo.CIDocuments", "ReadyForApproval", c => c.Boolean(nullable: false));
            AddColumn("dbo.CIDocuments", "ProjectFlag", c => c.String());
            AddColumn("dbo.CIDocuments", "ProjectApprovalStatus", c => c.String());
            AddColumn("dbo.CIDocuments", "ProcessOwner", c => c.String());
            AddColumn("dbo.CIDocuments", "Opprotunity", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "NextMeetingDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "ModifiedBy", c => c.String());
            AddColumn("dbo.CIDocuments", "Modified", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "MeetsAuditRequirements", c => c.Boolean(nullable: false));
            AddColumn("dbo.CIDocuments", "LastAuditDateTwo", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "LastAuditDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "EmployeeSiteNumber", c => c.String());
            AddColumn("dbo.CIDocuments", "CustomerBlackbelt", c => c.String());
            AddColumn("dbo.CIDocuments", "CustomerApproval", c => c.String());
            AddColumn("dbo.CIDocuments", "CustLevelThreeDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "CustLevelTwoDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "CustLevelTwo", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "CustLevelOneDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "CustFinancialEntryName", c => c.String());
            AddColumn("dbo.CIDocuments", "CreatedBy", c => c.String());
            AddColumn("dbo.CIDocuments", "Created", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "Contributors", c => c.String());
            AddColumn("dbo.CIDocuments", "CompletedDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "CompleteDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "Comments", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "Classification", c => c.String());
            AddColumn("dbo.CIDocuments", "CiNumber", c => c.Int(nullable: false));
            AddColumn("dbo.CIDocuments", "CheckedOutTo", c => c.String());
            AddColumn("dbo.CIDocuments", "Auditor", c => c.String());
            AddColumn("dbo.CIDocuments", "AtsLevelThreeDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "AtsLevelThree", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "AtsLevelTwoDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "AtsLevelTwo", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "AtsLevelOneDetails", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "AreaManager", c => c.String());
            AddColumn("dbo.CIDocuments", "ApprovalComments", c => c.Long(nullable: false));
            AddColumn("dbo.CIDocuments", "ActualSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "ThreeUpManager", c => c.String());
            AddColumn("dbo.CIDocuments", "TwoUpManager", c => c.String());
            AddColumn("dbo.CIDocuments", "OnePercentLevelOneEligible", c => c.Int(nullable: false));
            AddColumn("dbo.CIDocuments", "DivisionNumber", c => c.Int(nullable: false));
            AddColumn("dbo.CIDocuments", "TimeFrameSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "AtsExpectedSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "CustomerExpectedSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "FlagForDeletion", c => c.Boolean(nullable: false));
            AddColumn("dbo.CIDocuments", "OpenField2", c => c.String());
            AddColumn("dbo.CIDocuments", "OpenField1", c => c.String());
            AddColumn("dbo.CIDocuments", "Workorder", c => c.String());
            AddColumn("dbo.CIDocuments", "Blackbelt", c => c.String());
            AddColumn("dbo.CIDocuments", "OneUpManager", c => c.String());
            AddColumn("dbo.CIDocuments", "Region", c => c.String());
            AddColumn("dbo.CIDocuments", "FunctionalArea", c => c.String());
            AddColumn("dbo.CIDocuments", "CustActualSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "CustLevel3", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "CustLevel1", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "ATSLevel1", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "ATSActualSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "ProjectedSavings", c => c.Decimal(nullable: false, precision: 18, scale: 2));
            AddColumn("dbo.CIDocuments", "ProjectStatus", c => c.String());
            AddColumn("dbo.CIDocuments", "Benefits", c => c.String());
            AddColumn("dbo.CIDocuments", "ProjectPhase", c => c.String());
            AddColumn("dbo.CIDocuments", "ProjectType", c => c.String());
            AddColumn("dbo.CIDocuments", "WorkCompleteDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "ExpectedClose", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "StartDate", c => c.DateTime(nullable: false));
            AddColumn("dbo.CIDocuments", "Sponsor", c => c.String());
            AddColumn("dbo.CIDocuments", "ProjectLead", c => c.String());
            AddColumn("dbo.CIDocuments", "ProjectName", c => c.String());
            AddColumn("dbo.CIDocuments", "Name", c => c.String());
            AddColumn("dbo.CIDocuments", "SiteName", c => c.String());
            DropColumn("dbo.CIDocuments", "SiteProjectAppliesTo");
        }
    }
}
